# Generated by Django 6.0.5 on 2026-05-21 17:46

import apps.Bot.models.TelegramBot
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0011_appeal"),
    ]

    operations = [
        migrations.CreateModel(
            name="BotSetting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(max_length=100, unique=True, verbose_name="Kalit"),
                ),
                ("value", models.TextField(blank=True, verbose_name="Qiymat")),
            ],
            options={
                "verbose_name": "Bot sozlamasi",
                "verbose_name_plural": "Bot sozlamalari",
                "db_table": "bot_settings",
            },
        ),
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                (
                    "json_id",
                    models.IntegerField(blank=True, null=True, verbose_name="JSON ID"),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Kenglik"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Uzunlik"),
                ),
                (
                    "geo_address",
                    models.TextField(blank=True, verbose_name="Geopy manzil"),
                ),
                (
                    "geo_fetched",
                    models.BooleanField(default=False, verbose_name="Geo olindi"),
                ),
                (
                    "is_active",
                    models.BooleanField(default=False, verbose_name="Xizmat mavjud"),
                ),
                (
                    "delivery_price",
                    models.IntegerField(
                        default=0, verbose_name="Yetkazish narxi (so'm)"
                    ),
                ),
            ],
            options={
                "verbose_name": "Tuman",
                "verbose_name_plural": "Tumanlar",
                "db_table": "districts",
                "ordering": ["region__name", "name"],
            },
        ),
        migrations.CreateModel(
            name="Order",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "address_note",
                    models.TextField(verbose_name="Manzil izohi (va Tel)"),
                ),
                (
                    "delivery_slot",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Yetkazish vaqti",
                    ),
                ),
                (
                    "pickup_slot",
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name="Olib ketish vaqti",
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Kenglik"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Uzunlik"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("delivering", "Yuborilmoqda"),
                            ("done", "Yetkazildi"),
                            ("canceled", "Bekor qilindi"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "orders",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Region",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="Nomi")),
                ("json_id", models.IntegerField(unique=True, verbose_name="JSON ID")),
            ],
            options={
                "verbose_name": "Viloyat",
                "verbose_name_plural": "Viloyatlar",
                "db_table": "regions",
                "ordering": ["name"],
            },
        ),
        migrations.AlterModelOptions(
            name="telegramuser",
            options={
                "verbose_name": "Foydalanuvchi",
                "verbose_name_plural": "Foydalanuvchilar",
            },
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="best_streak",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="correct_answers",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="current_streak",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="highest_score",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="last_quiz_date",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="participated_quizzes_count",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="total_points",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="total_questions_answered",
        ),
        migrations.RemoveField(
            model_name="telegramuser",
            name="wrong_answers",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="bonus_points",
            field=models.IntegerField(default=0, verbose_name="Bonus ballar"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="lang",
            field=models.CharField(
                choices=[("uz", "O'zbek"), ("ru", "Русский"), ("en", "English")],
                default="uz",
                max_length=5,
                verbose_name="Til",
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="order_count",
            field=models.IntegerField(default=0, verbose_name="Buyurtmalar soni"),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="patient_id",
            field=models.CharField(
                default=apps.Bot.models.TelegramBot._generate_patient_id,
                max_length=20,
                unique=True,
                verbose_name="Bemor ID",
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="phone",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon"
            ),
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="role",
            field=models.CharField(
                choices=[
                    ("user", "Foydalanuvchi"),
                    ("courier", "Kuryer"),
                    ("doctor", "Shifokor"),
                    ("admin", "Admin"),
                ],
                default="user",
                max_length=20,
                verbose_name="Rol",
            ),
        ),
        migrations.AlterModelTable(
            name="telegramuser",
            table="telegram_users",
        ),
        migrations.AddField(
            model_name="telegramuser",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_users",
                to="Bot.district",
                verbose_name="Tuman",
            ),
        ),
        migrations.AddIndex(
            model_name="telegramuser",
            index=models.Index(fields=["role"], name="telegram_us_role_992135_idx"),
        ),
        migrations.AddIndex(
            model_name="telegramuser",
            index=models.Index(fields=["lang"], name="telegram_us_lang_00bb19_idx"),
        ),
        migrations.AddField(
            model_name="order",
            name="courier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="delivery_orders",
                to="Bot.telegramuser",
                verbose_name="Kuryer",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="district",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="Bot.district",
                verbose_name="Tuman",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="patient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="orders",
                to="Bot.telegramuser",
                verbose_name="Bemor",
            ),
        ),
        migrations.AddField(
            model_name="district",
            name="region",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="districts",
                to="Bot.region",
                verbose_name="Viloyat",
            ),
        ),
        migrations.AddIndex(
            model_name="district",
            index=models.Index(
                fields=["is_active"], name="districts_is_acti_a43f13_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="district",
            unique_together={("region", "name")},
        ),
    ]
