# Generated by Django 6.0.5 on 2026-05-22 00:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0012_botsetting_district_order_region_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Service",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_uz", models.CharField(max_length=255, verbose_name="Nomi (UZ)")),
                ("name_ru", models.CharField(max_length=255, verbose_name="Nomi (RU)")),
                ("name_en", models.CharField(max_length=255, verbose_name="Nomi (EN)")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Narxi (UZS)"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="Tavsif"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="Faol")),
            ],
            options={
                "verbose_name": "Xizmat",
                "verbose_name_plural": "Xizmatlar",
                "db_table": "services",
            },
        ),
        migrations.RemoveField(
            model_name="order",
            name="courier",
        ),
        migrations.RemoveField(
            model_name="order",
            name="delivery_slot",
        ),
        migrations.RemoveField(
            model_name="order",
            name="patient",
        ),
        migrations.RemoveField(
            model_name="order",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="order",
            name="base_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="child_timing",
            field=models.CharField(
                blank=True,
                choices=[
                    ("morning", "Ertalab"),
                    ("day", "Kundan keyin"),
                    ("evening", "Kechki payt"),
                    ("irregular", "Noma`lum"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="complaints",
            field=models.JSONField(
                blank=True, default=list, verbose_name="Shikoyatlar ro'yxati"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="custom_complaint",
            field=models.TextField(
                blank=True, null=True, verbose_name="Boshqa shikoyatlar"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="extra_fee",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name="order",
            name="patient_age",
            field=models.IntegerField(blank=True, null=True, verbose_name="Yoshi"),
        ),
        migrations.AddField(
            model_name="order",
            name="patient_gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Erkak"), ("female", "Ayol")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="patient_name",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="Bemor F.I.Sh"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="patient_type",
            field=models.CharField(
                blank=True,
                choices=[("adult", "Katta yoshli"), ("child", "Bola")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="total_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=12, null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="web_orders",
                to="Bot.telegramuser",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="uses_diaper",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="address_note",
            field=models.TextField(blank=True, null=True, verbose_name="Manzil izohi"),
        ),
        migrations.AlterField(
            model_name="order",
            name="district",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Bot.district",
                verbose_name="Tuman",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="pickup_slot",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="Olib ketish vaqti"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("paid", "To`langan"),
                    ("delivering", "Yo`lda"),
                    ("done", "Yetkazildi"),
                    ("canceled", "Bekor qilindi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterModelTable(
            name="order",
            table="web_orders",
        ),
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "method",
                    models.CharField(
                        choices=[
                            ("admin", "Admin orqali (Karta/Screnshot)"),
                            ("tpay", "Tpay (Onlayn Karta)"),
                        ],
                        max_length=10,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Kutilmoqda"),
                            ("success", "Muvaffaqiyatli"),
                            ("failed", "Xatolik"),
                        ],
                        default="pending",
                        max_length=15,
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    "card_mask",
                    models.CharField(
                        blank=True,
                        max_length=20,
                        null=True,
                        verbose_name="Karta maskasi",
                    ),
                ),
                (
                    "screenshot",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="payment_screenshots/",
                        verbose_name="Admin uchun chek rasmi",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="Bot.order",
                    ),
                ),
            ],
            options={
                "db_table": "payments",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="service",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="Bot.service",
                verbose_name="Tanlangan xizmat",
            ),
        ),
    ]
