# Generated by Django 6.0.5 on 2026-05-22 10:57

import apps.Bot.models.orders
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0013_service_remove_order_courier_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TestResult",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "doctor_conclusion",
                    models.TextField(
                        blank=True, null=True, verbose_name="Shifokor xulosasi / Izoh"
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to=apps.Bot.models.orders.get_result_upload_path,
                        verbose_name="Natija fayli (PDF/Rasm)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("processing", "Jarayonda / Tekshirilmoqda"),
                            ("ready", "Natija tayyor (Tasdiqlangan)"),
                            ("sent", "Mijozga yuborildi"),
                        ],
                        default="processing",
                        max_length=20,
                        verbose_name="Natija holati",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Oxirgi o'zgarish vaqti"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan vaqt"
                    ),
                ),
                (
                    "doctor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="issued_results",
                        to="Bot.telegramuser",
                        verbose_name="Mas'ul Shifokor (Telegram)",
                    ),
                ),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="test_result",
                        to="Bot.order",
                        verbose_name="Buyurtma",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tahlil natijasi",
                "verbose_name_plural": "Tahlil natijalari",
                "db_table": "test_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
