# Generated by Django 6.0.5 on 2026-05-22 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0014_testresult"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="district",
            name="json_id",
        ),
        migrations.RemoveField(
            model_name="region",
            name="json_id",
        ),
    ]
