# Generated by Django 6.0.5 on 2026-05-22 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0015_remove_district_json_id_remove_region_json_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="telegramuser",
            name="phone_number",
            field=models.CharField(
                blank=True, max_length=20, null=True, verbose_name="Telefon raqami"
            ),
        ),
    ]
