# Generated by Django 6.0.5 on 2026-05-23 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0016_telegramuser_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Kutilmoqda"),
                    ("paid", "To`langan"),
                    ("delivering", "Yo`lda"),
                    ("done", "Yetkazildi"),
                    ("result_pending", "Natija kutilmoqda"),
                    ("result_sent", "Natija jo`natildi"),
                    ("canceled", "Bekor qilindi"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
