# Generated by Django 6.0.5 on 2026-06-05 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Bot", "0020_telegramuser_lang_chosen"),
    ]

    operations = [
        migrations.AlterField(
            model_name="service",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Tavsif (qisqa)"
            ),
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        blank=True,
                        choices=[
                            (1, "⭐"),
                            (2, "⭐⭐"),
                            (3, "⭐⭐⭐"),
                            (4, "⭐⭐⭐⭐"),
                            (5, "⭐⭐⭐⭐⭐"),
                        ],
                        null=True,
                        verbose_name="Baholash (1-5)",
                    ),
                ),
                (
                    "text",
                    models.TextField(blank=True, null=True, verbose_name="Fikr matni"),
                ),
                (
                    "is_suggestion_only",
                    models.BooleanField(default=False, verbose_name="Faqat taklif"),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Yaratilgan sana"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="feedbacks",
                        to="Bot.telegramuser",
                        verbose_name="Foydalanuvchi",
                    ),
                ),
            ],
            options={
                "verbose_name": "Fikr va baholash",
                "verbose_name_plural": "Fikr va baholashlar",
                "db_table": "feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
